# Generated by Django 4.2.5 on 2023-09-17 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paturica', '0002_handmadepic_in_carousel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='handmadepic',
            old_name='pic',
            new_name='pic_obj',
        ),
        migrations.RemoveField(
            model_name='handmadepic',
            name='name',
        ),
    ]
