# Generated by Django 4.2.5 on 2023-09-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paturica', '0004_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='handmadepic',
            name='name',
            field=models.CharField(default='Handmade Object', max_length=255),
        ),
    ]
