# Generated by Django 4.2.5 on 2023-09-18 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paturica', '0005_handmadepic_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('material', models.CharField(max_length=400)),
                ('info', models.TextField(max_length=800)),
                ('pic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paturica.handmadepic')),
            ],
        ),
    ]
